CREATE TABLE TB_VITALIA_APP_USER (
                                     USER_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                                     FULL_NAME VARCHAR2(150) NOT NULL,
                                     EMAIL VARCHAR2(150) NOT NULL UNIQUE,
                                     PASSWORD_HASH VARCHAR2(255) NOT NULL,
                                     PHONE VARCHAR2(30),
                                     STATUS VARCHAR2(20) NOT NULL,
                                     CREATED_AT TIMESTAMP(6) NOT NULL,
                                     UPDATED_AT TIMESTAMP(6) NOT NULL,
                                     PRIMARY KEY (USER_ID)
);