CREATE TABLE accounts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          active BOOLEAN,
                          created_at TIMESTAMP(6),
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          role VARCHAR(50),
                          PRIMARY KEY (id)
);