CREATE TABLE app_user (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          full_name VARCHAR2(255) NOT NULL,
                          email VARCHAR2(255) NOT NULL UNIQUE,
                          password VARCHAR2(255) NOT NULL
);

CREATE TABLE role (
                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE app_user_roles (
                                user_id NUMBER NOT NULL,
                                role_id NUMBER NOT NULL,
                                PRIMARY KEY (user_id, role_id),
                                CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user(id),
                                CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE species (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR2(100) NOT NULL
);

CREATE TABLE breed (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR2(100) NOT NULL,
                       species_id NUMBER NOT NULL,
                       CONSTRAINT fk_breed_species FOREIGN KEY (species_id) REFERENCES species(id)
);

CREATE TABLE pet (
                     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR2(100) NOT NULL,
                     age NUMBER,
                     weight NUMBER(5,2),
                     breed_id NUMBER,
                     tutor_id NUMBER,
                     CONSTRAINT fk_pet_breed FOREIGN KEY (breed_id) REFERENCES breed(id),
                     CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_id) REFERENCES app_user(id)
);

CREATE TABLE appointment (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             appointment_date TIMESTAMP NOT NULL,
                             description VARCHAR2(500),
                             pet_id NUMBER NOT NULL,
                             vet_id NUMBER NOT NULL,
                             CONSTRAINT fk_appointment_pet FOREIGN KEY (pet_id) REFERENCES pet(id),
                             CONSTRAINT fk_appointment_vet FOREIGN KEY (vet_id) REFERENCES app_user(id)
);

CREATE TABLE clinical_history (
                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  record_date TIMESTAMP NOT NULL,
                                  notes CLOB,
                                  pet_id NUMBER NOT NULL,
                                  vet_id NUMBER NOT NULL,
                                  CONSTRAINT fk_history_pet FOREIGN KEY (pet_id) REFERENCES pet(id),
                                  CONSTRAINT fk_history_vet FOREIGN KEY (vet_id) REFERENCES app_user(id)
);

CREATE TABLE alert (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       message VARCHAR2(255) NOT NULL,
                       alert_date TIMESTAMP NOT NULL,
                       pet_id NUMBER NOT NULL,
                       CONSTRAINT fk_alert_pet FOREIGN KEY (pet_id) REFERENCES pet(id)
);