CREATE TABLE responsibles (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              account_id BIGINT UNIQUE,
                              address VARCHAR(255),
                              cpf VARCHAR(255) UNIQUE,
                              date_of_birth DATE,
                              full_name VARCHAR(255),
                              phone_number VARCHAR(255),
                              PRIMARY KEY (id),
                              CONSTRAINT FKnpwesn5nxwvibmlyebymajdiq FOREIGN KEY (account_id) REFERENCES accounts(id)
);