CREATE TABLE veterinarians (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               account_id BIGINT UNIQUE,
                               cpf VARCHAR(255),
                               crmv VARCHAR(255),
                               full_name VARCHAR(255),
                               speciality VARCHAR(255),
                               PRIMARY KEY (id),
                               CONSTRAINT FKkbh3kgclsmx8d8w52isabw6jp FOREIGN KEY (account_id) REFERENCES accounts(id)
);