CREATE TABLE pets (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      responsible_id BIGINT,
                      veterinarian_id BIGINT,
                      birth_date DATE,
                      weight FLOAT(53),
                      breed VARCHAR(255),
                      gender VARCHAR(255),
                      name VARCHAR(255),
                      species VARCHAR(255),
                      current_status VARCHAR(50),
                      PRIMARY KEY (id),
                      CONSTRAINT FKd8smuy5bi6nl1g3r1yiyxr20c FOREIGN KEY (responsible_id) REFERENCES responsibles(id),
                      CONSTRAINT FK9rrw99ugjexx1fshj8b2c6m9w FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id)
);