CREATE TABLE appointments (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              pet_id BIGINT NOT NULL,
                              veterinarian_id BIGINT NOT NULL,
                              appointment_date TIMESTAMP(6) NOT NULL,
                              created_at TIMESTAMP(6),
                              diagnosis TEXT,
                              reason VARCHAR(255) NOT NULL,
                              recommendation TEXT,
                              status VARCHAR(50),
                              PRIMARY KEY (id),
                              CONSTRAINT FK62dl3dvwsbveq3vv067becwmj FOREIGN KEY (pet_id) REFERENCES pets(id),
                              CONSTRAINT FKh0nkc9wb1n2pg5j51tpe23o5a FOREIGN KEY (veterinarian_id) REFERENCES veterinarians(id)
);