CREATE TABLE clinical_histories (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    pet_id BIGINT,
                                    heart_rate INT,
                                    temperature FLOAT(53),
                                    health_score FLOAT(53),
                                    recorded_at TIMESTAMP(6),
                                    activity_level VARCHAR(255),
                                    description TEXT,
                                    observations TEXT,
                                    PRIMARY KEY (id),
                                    CONSTRAINT FK362w9v5b7xwbdvtdcud1okc23 FOREIGN KEY (pet_id) REFERENCES pets(id)
);