CREATE TABLE alerts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        pet_id BIGINT,
                        created_at TIMESTAMP(6),
                        resolved_at TIMESTAMP(6),
                        message VARCHAR(255),
                        risk_level VARCHAR(50),
                        status VARCHAR(50),
                        type VARCHAR(50),
                        PRIMARY KEY (id),
                        CONSTRAINT FKosetet0qqu99htci1an5usc11 FOREIGN KEY (pet_id) REFERENCES pets(id)
);